# Generated by Django 4.1.1 on 2022-10-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makeinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrlmnt1', models.CharField(max_length=11)),
                ('addno1', models.CharField(max_length=13)),
                ('name1', models.CharField(max_length=200)),
                ('phoneno1', models.CharField(max_length=10)),
                ('email1', models.CharField(max_length=122)),
            ],
        ),
    ]
