# Generated by Django 4.1.1 on 2022-10-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gupms', '0002_contact_delete_makeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makeinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addmission', models.CharField(max_length=200)),
                ('enrollno', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=122)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
