# Generated by Django 4.1.1 on 2022-10-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gupms', '0003_makeinfo_delete_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Makeinfo',
            new_name='Contact',
        ),
    ]
