# Generated by Django 4.1.1 on 2022-10-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gupms', '0004_rename_makeinfo_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='addmission',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='enrollno',
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
