# Generated by Django 4.1.1 on 2022-10-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gupms', '0005_remove_contact_addmission_remove_contact_enrollno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment1', models.CharField(max_length=30)),
                ('admission1', models.CharField(max_length=30)),
                ('name1', models.CharField(max_length=30)),
                ('email1', models.EmailField(max_length=254)),
                ('phone1', models.CharField(max_length=30)),
                ('enrollment2', models.CharField(max_length=30)),
                ('admission2', models.CharField(max_length=30)),
                ('name2', models.CharField(max_length=30)),
                ('email2', models.EmailField(max_length=254)),
                ('phone2', models.CharField(max_length=30)),
                ('enrollment3', models.CharField(max_length=30)),
                ('admission3', models.CharField(max_length=30)),
                ('name3', models.CharField(max_length=30)),
                ('email3', models.EmailField(max_length=254)),
                ('phone3', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
