# Generated by Django 4.1.1 on 2022-11-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gupms', '0006_team_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='regnumber',
            field=models.IntegerField(null=True),
        ),
    ]
