# Generated by Django 4.1.1 on 2022-11-26 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gupms', '0007_team_regnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fourth_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnumber', models.IntegerField(null=True)),
                ('enrollment10', models.CharField(max_length=30)),
                ('admission10', models.CharField(max_length=30)),
                ('name10', models.CharField(max_length=30)),
                ('email10', models.EmailField(max_length=254)),
                ('phone10', models.CharField(max_length=30)),
                ('enrollment11', models.CharField(max_length=30)),
                ('admission11', models.CharField(max_length=30)),
                ('name11', models.CharField(max_length=30)),
                ('email11', models.EmailField(max_length=254)),
                ('phone11', models.CharField(max_length=30)),
                ('enrollment12', models.CharField(max_length=30)),
                ('admission12', models.CharField(max_length=30)),
                ('name12', models.CharField(max_length=30)),
                ('email12', models.EmailField(max_length=254)),
                ('phone12', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Second_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnumber', models.IntegerField(null=True)),
                ('enrollment4', models.CharField(max_length=30)),
                ('admission4', models.CharField(max_length=30)),
                ('name4', models.CharField(max_length=30)),
                ('email4', models.EmailField(max_length=254)),
                ('phone4', models.CharField(max_length=30)),
                ('enrollment5', models.CharField(max_length=30)),
                ('admission5', models.CharField(max_length=30)),
                ('name5', models.CharField(max_length=30)),
                ('email5', models.EmailField(max_length=254)),
                ('phone5', models.CharField(max_length=30)),
                ('enrollment6', models.CharField(max_length=30)),
                ('admission6', models.CharField(max_length=30)),
                ('name6', models.CharField(max_length=30)),
                ('email6', models.EmailField(max_length=254)),
                ('phone6', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Third_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnumber', models.IntegerField(null=True)),
                ('enrollment7', models.CharField(max_length=30)),
                ('admission7', models.CharField(max_length=30)),
                ('name7', models.CharField(max_length=30)),
                ('email7', models.EmailField(max_length=254)),
                ('phone7', models.CharField(max_length=30)),
                ('enrollment8', models.CharField(max_length=30)),
                ('admission8', models.CharField(max_length=30)),
                ('name8', models.CharField(max_length=30)),
                ('email8', models.EmailField(max_length=254)),
                ('phone8', models.CharField(max_length=30)),
                ('enrollment9', models.CharField(max_length=30)),
                ('admission9', models.CharField(max_length=30)),
                ('name9', models.CharField(max_length=30)),
                ('email9', models.EmailField(max_length=254)),
                ('phone9', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Team',
            new_name='First_year',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forget_password_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
