# Generated by Django 4.1.1 on 2022-11-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gupms', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='regnumber',
            field=models.IntegerField(null=True),
        ),
    ]
