# Generated by Django 4.1.1 on 2022-11-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gupms', '0003_team_regnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='regnumber',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
