# Generated by Django 4.1.1 on 2022-11-08 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gupms', '0006_rename_email1_team_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='email',
            new_name='email1',
        ),
    ]
