# Generated by Django 4.1.1 on 2022-11-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gupms', '0007_rename_email_team_email1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fourth_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnumber', models.IntegerField(null=True)),
                ('enrollment1', models.CharField(max_length=30)),
                ('admission1', models.CharField(max_length=30)),
                ('name1', models.CharField(max_length=30)),
                ('email1', models.EmailField(max_length=254)),
                ('phone1', models.CharField(max_length=30)),
                ('enrollment2', models.CharField(max_length=30)),
                ('admission2', models.CharField(max_length=30)),
                ('name2', models.CharField(max_length=30)),
                ('email2', models.EmailField(max_length=254)),
                ('phone2', models.CharField(max_length=30)),
                ('enrollment3', models.CharField(max_length=30)),
                ('admission3', models.CharField(max_length=30)),
                ('name3', models.CharField(max_length=30)),
                ('email3', models.EmailField(max_length=254)),
                ('phone3', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Second_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnumber', models.IntegerField(null=True)),
                ('enrollment4', models.CharField(max_length=30)),
                ('admission4', models.CharField(max_length=30)),
                ('name4', models.CharField(max_length=30)),
                ('email4', models.EmailField(max_length=254)),
                ('phone4', models.CharField(max_length=30)),
                ('enrollment5', models.CharField(max_length=30)),
                ('admission5', models.CharField(max_length=30)),
                ('name5', models.CharField(max_length=30)),
                ('email5', models.EmailField(max_length=254)),
                ('phone5', models.CharField(max_length=30)),
                ('enrollment6', models.CharField(max_length=30)),
                ('admission6', models.CharField(max_length=30)),
                ('name6', models.CharField(max_length=30)),
                ('email6', models.EmailField(max_length=254)),
                ('phone6', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Third_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regnumber', models.IntegerField(null=True)),
                ('enrollment1', models.CharField(max_length=30)),
                ('admission1', models.CharField(max_length=30)),
                ('name1', models.CharField(max_length=30)),
                ('email1', models.EmailField(max_length=254)),
                ('phone1', models.CharField(max_length=30)),
                ('enrollment2', models.CharField(max_length=30)),
                ('admission2', models.CharField(max_length=30)),
                ('name2', models.CharField(max_length=30)),
                ('email2', models.EmailField(max_length=254)),
                ('phone2', models.CharField(max_length=30)),
                ('enrollment3', models.CharField(max_length=30)),
                ('admission3', models.CharField(max_length=30)),
                ('name3', models.CharField(max_length=30)),
                ('email3', models.EmailField(max_length=254)),
                ('phone3', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Team',
            new_name='First_year',
        ),
    ]
